language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
  - dotnet build src/Serialize.Linq.NetStandard16/Serialize.Linq.NetStandard16.csproj --configuration Debug
  - dotnet build src/Serialize.Linq.NetStandard16/Serialize.Linq.NetStandard16.csproj --configuration Release
  - dotnet test src/Serialize.Linq.NetStandard16.Tests/Serialize.Linq.NetStandard16.Tests.csproj --configuration Debug
  - dotnet test src/Serialize.Linq.NetStandard16.Tests/Serialize.Linq.NetStandard16.Tests.csproj --configuration Release
after_success:
 - (cd src/Serialize.Linq.NetStandard16 && bash publish.sh Serialize.Linq.NetStandard16)
cache:
  directories:
  - $HOME/.nuget